import type { Metadata } from "next";
import { Roboto, Shantell_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "./storeProvider";

const poetseone = localFont({
  src: "../../public/fonts/PoetsenOne-Regular.otf",
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const shantellSans = Shantell_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {" "}
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
